### ISSUE TITLE
feat: data transfer between main <-> result

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#10]
### What is this issue? 🚀
메인 페이지 <-> 검색 결과 페이지 간 정보 공유를 위한 수정

### TODO 🏃‍♀️
- [x] 정보 전달 함수 구현
- [x] 정보 전달 여부 테스트
- [x] 정보 업데이트 여부 테스트

**Comment by Sungtae124** [comment]
Finished
