### ISSUE TITLE
feat: 검색 결과 페이지 내 검색 기능 업데이트

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#11]
### What is this issue? 🚀
검색 결과 페이지 내 검색 기능 긴급 추가

### TODO 🏃‍♀️
- [x] 검색 결과 페이지 내 검색 기능 업데이트
- [x] 추천 검색어 팝업 정상 동작 확인
- [x] 검색 결과 페이지 정상 업데이트 확인

**Comment by Sungtae124** [comment]
Finished
