### ISSUE TITLE
feat: 아티스트 상세 페이지 구현 및 메인 페이지와 연결

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#14]
### What is this issue? 🚀
아티스트 추천 박스 클릭 시 표시될 아티스트 페이지 구현

### TODO 🏃‍♀️
- [ ] 아티스트 페이지 구현
  - [ ] 페이지 기획
  - [ ] 페이지 구현
- [ ] 메인 페이지의 아티스트 추천 박스 클릭 시 페이지 연결
- [ ] 전체 구현 테스트

**Comment by Sungtae124** [comment]
아티스트 페이지 구현 대신 검색 결과 페이지에 아티스트 이름으로 키워드 검색을 통해 구현
