### ISSUE TITLE
feat: 메인 & 결과 페이지 pip 및 실제 재생 구현

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#16]
### What is this issue? 🚀
메인 페이지 & 결과 페이지 pip, 재생 기능 구현

### TODO 🏃‍♀️
- [x] 메인 페이지 pip 설정
- [x] 메인 페이지 재생기능 구현
- [x] 결과 페이지 pip 설정
- [x] 결과 페이지 재생기능 구현
- [x] 세부 페이지 -> 기존 페이지(메인 or 결과) 내 pip로 이동 기능 구현
- [x] 기존 페이지 -> 세부페이지 재연결 기능 구현
