### ISSUE TITLE
design: 세부 페이지 css 수정

### ISSUE THREAD

**Issue by cheoljinn** [Sungtae124/WebP_2024#18]
### What is this issue? 🚀
세부 페이지 css 마무리

### TODO 🏃‍♀️
- [x] 레코드판 사이즈 조정
- [x] 아티스트 이미지 비율 조정
- [ ] 좋아요 버튼 토글 구현
