### ISSUE TITLE
feat: Develop Detail Page

### ISSUE THREAD

**Issue by cheoljinn** [Sungtae124/WebP_2024#2]
### What is this issue? 🚀
세부 페이지 이슈 등록

### TODO 🏃‍♀️
- [x] 기본 틀 구현
- [ ] 배경색 바꾸는 시스템 도전!
- [x] 사이드 패널 구현
- [x] 메인 패널 이동 구현
- [x] API 연동
- [ ] 디자인 수정

**Comment by Sungtae124** [comment]
음원 세부 페이지 아티스트 버튼 클릭 시 나오는 아티스트 이미지 비율이 안 맞습니다..!
