### ISSUE TITLE
BugFix: Main Page bug fix

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#4]
### What is this issue? 🚀
메인 페이지 버그 수정을 위한 이슈 등록

### TODO 🏃‍♀️
- [ ] API 키 정상 분리를 통한 페이지 내 실제 정보 표시 구현
- [x] PiP 기능 정상화
- [x] 다른 장르 변환 버튼 실제 구현
- [ ] 실제 재생 기능 구현

**Comment by Sungtae124** [comment]
모든 기능 수정은 새로운 브랜치에서 진행 예정
