### ISSUE TITLE
feat: Result Page Development

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#5]
## What is this issue? 🚀
검색 결과 페이지 개발을 위한 이슈 등록

## TODO 🏃‍♀️
- [x] 검색창 디자인 변경
- [x] 검색 결과 음원별 박스 레이아웃 구현
- [ ] 박스 클릭 이벤트를 재생 기능과 연결
- [ ] 메인 페이지와 연결(검색 키워드 전달)
- [ ] 음원 세부 페이지와 연결

**Comment by Sungtae124** [comment]
모든 기능 수정은 새로운 브랜치에서 진행 예정
