### ISSUE TITLE
feat: Develop Login Pop-Up

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#6]
### What is this issue? 🚀
메인 페이지 및 검색 결과 페이지 내 재생 시 로그인 필요 창 팝업 구현

### TODO 🏃‍♀️
- [x] 로그인 팝업 창 구현
- [ ] 로그인 기능 연결
- [x] 메인 페이지 및 검색 페이지에 기능 추가

**Comment by Sungtae124** [comment]
모든 기능 수정은 새로운 브랜치에서 진행 예정
