### ISSUE TITLE
modify: Integration development fixes

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/WebP_2024#9]
### What is this issue? 🚀
전체 페이지 수정을 위한 브랜치 및 이슈
- 각 수정 사항별 브랜칭 및 이슈 전략 사용할 것

### TODO 🏃‍♀️
- [ ] 세부 페이지 오류 수정 후 메인에 병합
- [ ] API 관련 기능 구현을 위한 코드 수정
  - [ ] API 관련 키 분리 or 로컬 서버 생성 후 authorization 진행
  - [x] 전체 페이지 재생 기능
  - [x] 로그인 기능
- [ ] 각 페이지 연결 정보 전달 구현을 위한 코드 수정
  - [x] 메인 페이지 <-> 결과 페이지 정보 전달
